### ISSUE TITLE
Crash of Sopare when exceeding threshold - using numpy >=1.13

### ISSUE THREAD

**Issue by Ringo96** [bishoph/sopare#10]
Hello,

i've already written you on your blog and opened now the issue like you suggested.
https://www.bishoph.org/sopare-precision-and-accuracy/#comment-198

So the program crashed as soon as the sound level got over threshold with the following message:

> Process buffering queue:
Traceback (most recent call last):
File „/usr/lib/python2.7/multiprocessing/process.py“, line 258, in _bootstrap
self.run()
File „/home/pi/testing_sopare/sopare/buffering.py“, line 43, in run
self.proc.check_silence(buf)
File „/home/pi/testing_sopare/sopare/processing.py“, line 74, in check_silence
self.prepare.prepare(buf, volume)
File „/home/pi/testing_sopare/sopare/prepare.py“, line 125, in prepare
self.tokenize(meta)
File „/home/pi/testing_sopare/sopare/prepare.py“, line 50, in tokenize
self.filter.filter(self.buffer, meta)
File „/home/pi/testing_sopare/sopare/filter.py“, line 130, in filter
if (shift_fft != None and self.cfg.hasoption(‚experimental‘, ‚FFT_SHIFT‘) and self.cfg.getbool(‚experimental‘, ‚FFT_SHIFT‘) == True):

I've tried the change you suggested
`if ((shift_fft is not None) and self.cfg.hasoption('experimental', 'FFT_SHIFT') and self.cfg.getbool('experimental', 'FFT_SHIFT') == True):`
at line 130 in the filter.py and it **works**!
The program is now working and I will start training words :)
Thanks very much!

**Comment by bishoph** [comment]
Cool, thanks. The fix will be released with the 1.5.0 release/merge within the next days.
