### ISSUE TITLE
Q: SIMILARITY_ZERO_CROSSING_RATE

### ISSUE THREAD

**Issue by cs301cs301** [bishoph/sopare#21]
I need help,

you mentioned i should add "SIMILARITY_ZERO_CROSSING_RATE", but i dont't know where to add and which value it needs.

Pls give me a hint. :)

thx

**Comment by bishoph** [comment]
This is an example of my current config (config/default.ini)

<pre>

#########################################################
# Compare configuration options #########################
#########################################################

[compare]

# Min. number of tokens to identify the beginning of a word
MIN_START_TOKENS = 3

# Min. value for potential beginning of a word
MARGINAL_VALUE = 0.8

# Minimal similarity across all comparison to
# identify a complete word across all tokens
MIN_CROSS_SIMILARITY = 0.85

# Calculation basis or token/word comparison
# 0.6, 0.2, 0, 0.2
SIMILARITY_NORM = 0.5
SIMILARITY_HEIGHT = 0.2
SIMILARITY_DOMINANT_FREQUENCY = 0
SIMILARITY_ZERO_CROSSING_RATE = 0.3


</pre>
