### ISSUE TITLE
Question: Do You Place All Your Code in The Output Folder?

### ISSUE THREAD

**Issue by snwdrft** [bishoph/sopare#24]
From watching your video on the magic mirror, it seemed like you compiled all your code into a folder called events in the output folder (/plugins/print/events/_init_.py). Is that the way to do it, or could you use an external compiler or IDE to do the same job?

**Comment by bishoph** [comment]
All folders in the plugin folder of SOPARE are python modules or packages. Here are links with helpful information:

https://www.bishoph.org/sopare-architecture-and-plugins/
https://docs.python.org/2/tutorial/modules.html

Of course you can use a text editor or an IDE to create and edit those files ;)

**Comment by snwdrft** [comment]
I've tried to see if the run function would print the values that are being produced by the program, but nothing seems to show up. It works perfectly fine in the terminal command line, but nothing shows up in the python shell.
