### ISSUE TITLE
Noise Filtering?

### ISSUE THREAD

**Issue by ankit-gaur** [bishoph/sopare#3]
First of all, thanks for developing this.
I want to ask that have you integrated something for noise filtering/cancellation from mic stream/wav file? I tried to look into the code but couldn't find.

**Comment by bishoph** [comment]
There is no specific noise cancellation. But SOPARE uses a configurable range of frequencies for the analysis.  Furthermore, SOPARE compresses the frequencies and creates a characteristic. And you have options to define the accuracy which helps to identify true positives with background noise or in different conditions.

Maybe you find this helpful: https://www.bishoph.org/sopare-precision-and-accuracy/

**Comment by bishoph** [comment]
Closing issue
