### ISSUE TITLE
divide by zero

### ISSUE THREAD

**Issue by cs301cs301** [bishoph/sopare#33]
Hi,

i set CHUNKS = 1024 and sometimes this occurs in training (mostly in the third training round of a word)...

/home/sopare/sopare/filter.py:138: RuntimeWarning: divide by zero encountered in log10
  shift_nfft = numpy.log10(nfft)**2
/home/sopare/sopare/filter.py:143: RuntimeWarning: invalid value encountered in divide
  shift_nfft = numpy.tanh(shift_nfft/shift_nam)

any idea?

thx

**Comment by bishoph** [comment]
This is a numpy warning message. I have to check if the input is zero before passing it to numpy. Will fix it with one of the next commits. Thanks for reporting :)

**Comment by bishoph** [comment]
Should be fixed with commit ca692ff in testing branch (version >= 1.5.4)
