### ISSUE TITLE
Recognition speed

### ISSUE THREAD

**Issue by classicryder** [bishoph/sopare#36]
Hi, i noticed that there is a delay in sopare when it recognizes a trained word, for example i make it to turn on the led if a trained word recognized, the result is there is like nearly 1 second delay until the led turns on.. which parameter in default.ini should i tweak to change this behavior?

**Comment by bishoph** [comment]
Hi. SOPARE starts the analysis after short gaps (like in a sentence):

LONG_SILENCE

or after a specified silence:

MAX_SILENCE_AFTER_START 

I would start by reducing the MAX_SILENCE_AFTER_START by short margins and try if this works for you.

**Comment by classicryder** [comment]
thanks! it works
