### ISSUE TITLE
alarm recognition

### ISSUE THREAD

**Issue by xastx** [bishoph/sopare#41]
is there any built-in function to detect different kind of alarm sounds? i tried to train it for police/ambulance siren, but failed. can it be succeeded? or is it just for voices?

**Comment by bishoph** [comment]
SOPARE is a sound recognition project and requires custom training. SOPARE does not come with any built in sound detection compilations and is not only for voice. You need clean and identifiable sound for training and recognition. If you want to deal with street noise and wants to detect a siren from far away SOPARE is maybe not the ideal project as you need a certain threshold for activation and you get too much noise for the recognition.
