### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by agyoo** [bishoph/sopare#46]
could you please tell me where the code specifically for the output is?
(where does it print the output directly?)

**Comment by agyoo** [comment]
hahaha sorry for not being so clear. 
I want to know which part of the code (specifically: which python file and which lines) causes the program(sopare) to print [u'test'] or [] when I run the program.

**Comment by bishoph** [comment]
It's the print plugin:

https://github.com/bishoph/sopare/blob/master/plugins/print/__init__.py
