### ISSUE TITLE
Is 'PROGRESSIVE_FACTOR' still used?

### ISSUE THREAD

**Issue by a3020** [bishoph/sopare#60]
I don't see the 'PROGRESSIVE_FACTOR' setting being referenced in the code. Am I missing something?

https://github.com/bishoph/sopare/blob/testing/config/default.ini#L40
https://github.com/bishoph/sopare/search?q=factor&unscoped_q=factor

**Comment by bishoph** [comment]
Sure, it is in the code as a simple "grep" shows.

**Comment by a3020** [comment]
@bishoph can you point me to the file + line number, please?

**Comment by a3020** [comment]
Well, I don't see it. But again, maybe I'm missing something...

![Screenshot from 2019-04-15 16-05-03](https://user-images.githubusercontent.com/1431100/56139013-522f2580-5f98-11e9-811a-c0f0f9d1fcfd.png)

**Comment by bishoph** [comment]
I don't see it either and I need a strong coffee ;) The variable PROGRESSIVE_FACTOR is not longer in use. Will remove it with one of the next commits.
