### ISSUE TITLE
regarding pi4 and python3

### ISSUE THREAD

**Issue by umsaenga** [bishoph/sopare#87]
`Python3 compatibility and testing, install guides`

Wanted to inform you I was able to successfully install (As per from the current instructions) and run on a pi 4 model B and raspian OS lite 
Version: May 2020
Release date: 2020-05-27
Kernel version: 4.19
python3

**Comment by bishoph** [comment]
Cool. Thx for the info!

**Comment by bishoph** [comment]
But Python3 still requires some work (hope I can work on this topic this fall), JFYI.

**Comment by umsaenga** [comment]
So far it's working fine for me, i can train it and now testing commands on a breadboard.  No issues so far

**Comment by umsaenga** [comment]
excellent work!! thank you for it. btw

**Comment by bishoph** [comment]
Glad that you like it and you are welcome :)

**Comment by tzukpolinsky** [comment]
HI
where does the Python3 compatibility and testing, install guides is?
i would like to try it myself as well

**Comment by umsaenga** [comment]
> 
> 
> HI
> where does the Python3 compatibility and testing, install guides is?
> i would like to try it myself as well

I simply followed the instructions in the current readme file and replaced the appropriate python3 commands.

**Comment by bishoph** [comment]
The current testing branch should work with Python 2 and 3, SOPARE version >= 1.5.6. In addition the readme contains the requirements for both versions.
